n((data) => console.log(data)).catch((error) => console.log(error));